Feat: add client option to use/not use weights provided by HSDO Server
M6Web/hsdo pull request #3
Opened 2021-10-29 08:25 UTC by QuentinBtd

### WHY ?

If you want to let HAProxy manage weights of servers with data collected by [Agent check](https://www.haproxy.com/documentation/hapee/latest/load-balancing/health-checking/agent-health-checks/), HSDO do not set weight in HAProxy, else Agent Check and HSDO will overwrite each other

### HOW ?

Add an option in HSDO client to use or not the weights managed by HSDO. 

HSDO server will continue to provide weights into DynamoDB but the client will not used it.

2021-10-29 08:53 UTC, tanguyfalconnet requested changes

2021-10-29 08:53 UTC, tanguyfalconnet commented on README.md
> +`CLIENT_USE_WEIGHTS_PROVIDED_BY_HSDO`: Use weights provide in DynamoDB by HSDO Server. Default to `true`.
```suggestion
`CLIENT_USE_WEIGHTS`: Use weights provided by HSDO Server. Default to `true`.
```

2021-10-29 08:53 UTC, tanguyfalconnet commented on src/client/haproxy.py
> +            if self.useProvidedWeights == "true":
```suggestion
            if self.useProvidedWeights:
```

2021-10-29 08:53 UTC, tanguyfalconnet commented on src/client/haproxy.py
> +        self.useProvidedWeights = Configuration().get("CLIENT_USE_WEIGHTS_PROVIDED_BY_HSDO")
```suggestion
        self.useProvidedWeights = Configuration().get("CLIENT_USE_WEIGHTS_PROVIDED_BY_HSDO") == "true"
```

2022-10-18 14:29 UTC, vgallissot commented
As we've discussed alltogether, we won't go further on this PR as we've decided that AgentCheck won't be very usefull in our case.

2022-10-18 14:29 UTC, closed without merging